### ISSUE TITLE
BT pairing ESP32 and IC-705 

### ISSUE THREAD

**Issue by dl5dla** [WillyIoBrok/CIVbusLib#1]
Thanks for the code. I initially tried the bluetooth example on an ESP32 connecting to my IC-705. Works fine out of the box: I am just wondering whether there is a way to pair both devices only once and not on each reset of the ESP32.

**Comment by WillyIoBrok** [comment]
Hi - don't know, whether I understood correctly. Therefore I'll explain the behaviour as I have experienced:
You only have to pair the IC705 once to the ESP32 manually. After pairing, the ESP32 is stored in the list of known devices in the IC705.
So, as long as the ESP32 device is switched on first and the IC705 later (a few seconds) the IC705 will automatically connect to the ESP32 device (if "Auto Connect" is set to ON in the menu of IC705 and ESP32 has been connected at switching off the IC705).

Is that what you mean?

73, Wilfried, DK8RW

P.s.: The ESP32 device is always called CIV_BT_IFC (fixed in the code) in the release 0.6 on Github. I needed to make the BT-name easily changeable for some reason and I would have a new release available. Is this something interesting for you also ?

**Comment by dl5dla** [comment]
Thanks Wilfried - ok, understood, I have to first switch the ESP device on and then the 705. I had expected the other way around, as it is e.g. for the mobile app ("705 remote"). Is that also possible with your code? The idea behind is to use the ESP32 to control my Elecraft T1 tuner. As the T1 stores its settings for each band, it should be possible to get the current band out of the 705 and then to tell the T1 to apply the right settings accordingly.

Thanks
 73 DL5DLA Peter

**Comment by WillyIoBrok** [comment]
Well, what you are willing to do should be easily possible with the civ class (but not the Icradio class building up on civ).
Btw. - I am developing just the same at the moment: Controlling the low pass filters of my homebrew 100W PA via BT / civ from the IC705 (frequency) ...

However, I still don't understand your issue of building up the BT connection between the IC705 and the ESP32 device ... they do simply connect like plugging in a cable. After that, you are free to do whatever you want. Anyhow, this is something which is set in the BT library and I have only basic user knowledge about that, so I can't help in this case, sorry ...

73, Wilfried, DK8RW

**Comment by dl5dla** [comment]
HI Wilfried,
>However, I still don't understand your issue of building up the BT connection ...

What I did:
(1) I have paired the ESP32 and the 705 by "Pairing/Connect" in the bluetooth section of the 705. The ESP32 was found, paired and connected. -> OK
(2) Monitoring the ESP32 print commands shows that the 705 sends data (frequency). -> OK
(3) When I switch off the 705  and on again, the connection is re-established ->OK
(4) but when I switch off the ESP32 and on again again, the connection is NOT re-established. I have to step into the menu and have to manually connect again, or alternatively have to switch the 705 off and on.

So, I am wondering whether in case (4) the 705 should also reconnect automatically, or whether the described behavior (4) is correct.

73 Peter

**Comment by WillyIoBrok** [comment]
Ok Peter, now I understand your issue, thanks for the explanation 😉
However, I can't help either, sorry. I am not too good in BT stacks ... what I guess (but don't know for sure!) is, that the IC705 is the BT master, the ESP32 is the BT slave, so only the master can setup the link, which is done by the IC 705 at bootup or manually. Whether the roles can be turned around I don't know, sorry. Maybe the docu of the library can help, maybe searching the internet about BT-basics can bring some more information.

73,

Wilfried
